Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu14"
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.hostname = 'changes-sails'

  config.vm.network :forwarded_port, guest: 9000, host: 9000

  config.vm.synced_folder ".", "/project"
  config.vm.synced_folder "~/vm-shared", "/vm-shared"

  config.vm.provision "shell", inline: ". /project/provision/provision.sh", privileged: false

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
end
